Fluent interface
pagemachine/authorized-keys pull request #34
Opened 2023-03-12 22:57 UTC by vokeit-gschuster

Added fluent interface and fromFile() for PublicKey

2023-03-14 07:07 UTC, mbrodala requested changes
Thanks for the suggestion, please have a look at my remarks.

2023-03-14 07:07 UTC, mbrodala commented on src/PublicKey.php
> +            throw new FilePermissionException(sprintf('Could not read file "%s"', $file), 1486563469);
Please use a unique code here (current UNIX timestamp).

2023-03-14 10:48 UTC, vokeit-gschuster commented
Fixed.

2023-03-15 10:24 UTC, mbrodala commented
Can you please allow editing of your fork/branch?

2023-03-16 06:09 UTC, mbrodala approved these changes

2023-03-16 06:09 UTC, merged

2023-03-16 06:12 UTC, mbrodala commented
I squashed all commits into one and added a missing exception import. Thanks for the contribution!

This was released now: https://github.com/pagemachine/authorized-keys/releases/tag/2.2.0